goggles_shop/authapp/urls.py
from django.conf.urls import url
from django.urls import path

import authapp.views as authapp
from .views import UserDelete, UserDetail


app_name = 'authapp'

urlpatterns = [
url(r'^login/$', authapp.login, name='login'),
url(r'^logout/$', authapp.logout, name='logout'),
url(r'^register/$', authapp.register, name='register'),
url(r'^edit/$', authapp.edit, name='edit'),
path('<int:pk>/delete', UserDelete.as_view(), name='user_delete'),
path('<int:pk>/', UserDetail.as_view(), name='user_detail'),
]

goggles_shop/goggles_shop/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls import include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^auth/', include('authapp.urls', namespace='auth')),
    path('', include('goggles.urls')),
    # re_path(r'^user', include('authapp.urls', namespace='auth')),
]

goggles_shop/authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatars', blank=True)
    age = models.PositiveIntegerField(verbose_name = 'возраст')

goggles_shop/authapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm

from authapp.models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')


    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super(ShopUserRegisterForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']

        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'email', 'age', 'avatar', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserEditForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']

        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data


class UserModelForm(forms.ModelForm):
    class Meta:
        model = ShopUser
        fields = ['username', 'age', 'avatar']

goggles_shop/authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    CreateView, UpdateView,
    DeleteView, ListView, DetailView,
)


from authapp.forms import ShopUserLoginForm
from authapp.forms import ShopUserRegisterForm
from authapp.forms import ShopUserEditForm
from .models import ShopUser
from .forms import UserModelForm


def login(request):
    title = 'вход'
    login_form = ShopUserLoginForm(data=request.POST)
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('index'))

    content = {'title': title, 'login_form': login_form}
    return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    title = 'регистрация'
    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))

    else:
        register_form = ShopUserRegisterForm()

    content = {'title': title, 'register_form': register_form}

    return render(request, 'authapp/register.html', content)


def edit(request):
    title = 'редактирование'
    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)

        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))

    else:
        edit_form = ShopUserEditForm(instance=request.user)

    content = {'title': title, 'edit_form': edit_form}

    return render(request, 'authapp/edit.html', content)



class UserDetail(DetailView):
    model = ShopUser
    template_name = 'authapp/detail.html'
    context_object_name = 'instance'

class UserDelete(DeleteView):
    model = ShopUser
    context_object_name = 'instance'
    template_name = 'authapp/delete.html'
    success_url = reverse_lazy('index')

goggles_shop/authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
   <head>
      <meta charset="utf-8">
      <title>
         {% block title %}
         {{ title|title }}
         {% endblock %}
      </title>
      {% block css %}
      <link rel="stylesheet" type="text/css" href="{% static
         'css/bootstrap.min.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'
         %}">
      <link rel="stylesheet" href="{% static
         'fonts/font-awesome/css/font-awesome.css' %}">
      {% endblock %}
      {% block js %}
      {% endblock %}
   </head>
   <body>
      <div class="container">
         <div class="login">
            <div class="h2 text-center head">
               Вход в систему
            </div>
            {% block content %}
            {% endblock %}
         </div>
      </div>
   </body>
</html>

goggles_shop/authapp/templates/authapp/delete.html
<p>{{instance}}</p>
<p>{{instance.age}}</p>

<form method="POST">
    {% csrf_token %}
    <input type="submit" value="DELETE">
</form>

goggles_shop/authapp/templates/authapp/detail.html
{% load staticfiles %}

<p>{{instance}}</p>
<p>{{instance.age}}</p>

goggles_shop/authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block content %}
<form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ edit_form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
</form>
<button class="btn btn-round form-control last">
    <a href="{% url 'index' %}" class="">
        на главную
    </a>
</button>
<div class="user_avatar"><img src="/media/{{ user.avatar }}"></div>
{% endblock %}

goggles_shop/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}
{% block content %}
<form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
   {% csrf_token %}
   {{ login_form.as_p }}
   <br>
   <input class="form-control" type="submit" value="войти">
</form>
<button class="btn btn-round form-control">
    <a href="{% url 'auth:register' %}" class="">
        зарегистрироваться
    </a>
</button>
{% endblock %}

goggles_shop/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block content %}
<form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ register_form.as_p }}
    <br>
    <input class="form-control" type="submit" value="зарегистрироваться">
</form>
{% endblock %}